---
version: "3.9"
services:
  web:
    image: python:3.9
    container_name: blog_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: >
      bash -c "pip install -r requirements.txt && python manage.py
      makemigrations && python manage.py migrate && python manage.py runserver
      0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=blogproject.settings
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: blogproject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: null
